### ISSUE TITLE
Attempting to call a function in a renderer window that has been closed or released

### ISSUE THREAD

**Issue by S--Minecraft** [BlitzModder/BMPC#32]
```
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: undefined
```

原因不明

**Comment by S--Minecraft** [comment]
```
Uncaught (in promise) Error: Could not call remote function 'gt'. Check that the function signature is correct. Underlying error: Invalid Version: undefined
Error: Could not call remote function 'gt'. Check that the function signature is correct. Underlying error: Invalid Version: undefined
    at callFunction (C:\Users\s\Documents\GitHub\BMPC\dist\win-unpacked\resources\electron.asar\browser\rpc-server.js:257:11)
    at EventEmitter.<anonymous> (C:\Users\s\Documents\GitHub\BMPC\dist\win-unpacked\resources\electron.asar\browser\rpc-server.js:357:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (C:\Users\s\Documents\GitHub\BMPC\dist\win-unpacked\resources\electron.asar\browser\api\web-contents.js:256:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at callFunction (C:\Users\s\Documents\GitHub\BMPC\dist\win-unpacked\resources\electron.asar\browser\rpc-server.js:257:11)
    at EventEmitter.<anonymous> (C:\Users\s\Documents\GitHub\BMPC\dist\win-unpacked\resources\electron.asar\browser\rpc-server.js:357:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (C:\Users\s\Documents\GitHub\BMPC\dist\win-unpacked\resources\electron.asar\browser\api\web-contents.js:256:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (C:\Users\s\Documents\GitHub\BMPC\dist\win-unpacked\resources\electron.asar\renderer\api\remote.js:228:13)
    at Function.remoteMemberFunction (C:\Users\s\Documents\GitHub\BMPC\dist\win-unpacked\resources\electron.asar\renderer\api\remote.js:118:18)
    at file:///C:/Users/s/Documents/GitHub/BMPC/dist/win-unpacked/resources/app.asar/gui/js/index.js:101:14
metaToValue @ C:\Users\s\Documents\GitHub\BMPC\dist\win-unpacked\resources\electron.asar\renderer\api\remote.js:228
remoteMemberFunction @ C:\Users\s\Documents\GitHub\BMPC\dist\win-unpacked\resources\electron.asar\renderer\api\remote.js:118
(anonymous) @ index.js:101
```

**Comment by S--Minecraft** [comment]
`teststart`では詳細なエラーが出ないのに`start`ではでる

tagのnameは""だったのが原因

2822a4c で修正
