### ISSUE TITLE
説明の画面を開くときにたまにクラッシュする

### ISSUE THREAD

**Issue by S--Minecraft** [BlitzModder/BMPC#33]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'teststart' ]
2 info using npm@3.9.3
3 info using node@v6.2.1
4 verbose run-script [ 'preteststart', 'teststart', 'postteststart' ]
5 info lifecycle BlitzModder@1.2.7~preteststart: BlitzModder@1.2.7
6 silly lifecycle BlitzModder@1.2.7~preteststart: no script for preteststart, continuing
7 info lifecycle BlitzModder@1.2.7~teststart: BlitzModder@1.2.7
8 verbose lifecycle BlitzModder@1.2.7~teststart: unsafe-perm in lifecycle true
9 verbose lifecycle BlitzModder@1.2.7~teststart: PATH: ~~省略~~;
10 verbose lifecycle BlitzModder@1.2.7~teststart: CWD: C:\Users\s\Documents\GitHub\BMPC
11 silly lifecycle BlitzModder@1.2.7~teststart: Args: [ '/d /s /c', 'node_modules\\electron\\dist\\electron.exe bin' ]
12 silly lifecycle BlitzModder@1.2.7~teststart: Returned: code: 255  signal: null
13 info lifecycle BlitzModder@1.2.7~teststart: Failed to exec teststart script
14 verbose stack Error: BlitzModder@1.2.7 teststart: `node_modules\electron\dist\electron.exe bin`
14 verbose stack Exit status 255
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid BlitzModder@1.2.7
16 verbose cwd C:\Users\s\Documents\GitHub\BMPC
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "teststart"
19 error node v6.2.1
20 error npm  v3.9.3
21 error code ELIFECYCLE
22 error BlitzModder@1.2.7 teststart: `node_modules\electron\dist\electron.exe bin`
22 error Exit status 255
23 error Failed at the BlitzModder@1.2.7 teststart script 'node_modules\electron\dist\electron.exe bin'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the BlitzModder package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node_modules\electron\dist\electron.exe bin
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs BlitzModder
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls BlitzModder
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by S--Minecraft** [comment]
二回説明の画面を開いたときにクラッシュする #34

**Comment by S--Minecraft** [comment]
electron 1.6.5では落ちる
1.6.2では落ちない

**Comment by S--Minecraft** [comment]
electron/electron #9231

**Comment by S--Minecraft** [comment]
修正がマージされたのでリリース待ち
